### ISSUE TITLE
use `repository` if it's a string

### ISSUE THREAD

**Issue by jonschlinkert** [helpers/helper-issue#2]
Currently this assumes the `owner` is me, instead of `assemble`. 

I think this could be simplified by removing the logic for `owner` and `repo` and requiring the user to pass in a single `repository` value with the same format expected by package.json: `assemble/assemble`. This way we can check the context for that value, and:

- if it's a string, parse it (to be sure it doesn't have `https://` etc), then stringify the repository
- if it's an object, do the same thing with `repository.url`

**Comment by doowb** [comment]
> Currently this assumes the owner is me, instead of assemble.

How is that? It would only use you as the owner if you passed `jonschlinkert` on the `owner` property. You can pass `assemble` on the `owner` property, or you can omit the `owner` property and pass something like `repo: 'assemble/assemble'`.

We could update it to allow passing an object or string on `repo` and do more parsing and normalizing to allow data to come into this helper from other places.

Btw... there is weird logic in here that isn't needed (like the `if` statement after the `deletes`). I'm not sure what I was thinking there.

**Comment by jonschlinkert** [comment]
> How is that?

I don't know, maybe there is a property on the context with incorrect info that's being used when only `title` or `body` are passed

**Comment by doowb** [comment]
Closed by #3
